export const FETCHING_ICOS='FETCHING_ICOS';
export const FETCHED_ICOS='FETCHED_ICOS';
export const FETCHED_FAILED='FETCHED_FAILED';
//export const SORT_ICO='SORT_ICO';
export const FETCHING_ICO_MARKS='FETCHING_ICO_MARKS';
export const FETCHED_ICO_MARKS='FETCHED_ICO_MARKS';
